name: CI Pipeline
on: [push, pull_request]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Run Linter
        run: npm run lint
        # QUALITY GATE: Fails on lint violations

      - name: Build project
        run: npm install && npm run build
        # QUALITY GATE: Fails on build errors

      - name: Run tests
        run: npm test
        # QUALITY GATE: Fails on test failures

      - name: Build Docker image
        run: docker build -t my-app .
        # Build Docker image for deployment

      - name: Push Docker image
        run: echo "${{ secrets.AZURE_SECRET_KEY }}" | docker login <your-docker-registry> --username <your-username> --password-stdin && docker push my-app
        # Push Docker image to registry for deployment